# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cam_cap.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CamCapWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1958, 1080)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: #4c4a48;")
        # MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        # MainWindow.setAnimated(True)
        self.mainframe = QtWidgets.QWidget(MainWindow)
        self.mainframe.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainframe.sizePolicy().hasHeightForWidth())
        self.mainframe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.mainframe.setFont(font)
        self.mainframe.setStyleSheet(
            "/* leave here to be overwritten by anything more specific */\n"
            "\n"
            "QWidget {\n"
            '    font-family: "Bahnschrift";\n'
            "}\n"
            "\n"
            "\n"
            "\n"
            "/* alphabetical from here */\n"
            "\n"
            "QCheckBox::indicator {\n"
            "    top: 2 px;\n"
            "    width: 13px;\n"
            "    height: 13px;\n"
            "    background-color: #f2f4f3;\n"
            "    border-radius: 2px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: #ffba00;\n"
            "    image: url(:/images/down.png);\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QComboBox {\n"
            "    border-radius: 5px;\n"
            "    padding-left: 10px;\n"
            "    min-width: 6em;\n"
            "    background: #F2F4F3;\n"
            '    font-family: "Bahnschrift";\n'
            "}\n"
            "\n"
            "QComboBox:on { /* shift the text when the popup opens */\n"
            "    border: 2px sold #F2F4F3;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down {\n"
            "    width: 25px;\n"
            "    background-color: #FFBA00;\n"
            "}\n"
            "\n"
            "QComboBox::down-arrow {\n"
            "    border-image: url(:/images/down.png);\n"
            "}\n"
            "\n"
            "QComboBox::drop-down::hover {\n"
            "    background-color: #FFC300;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down::pressed {\n"
            "    background-color: #88AB75;\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView {\n"
            "    selection-background-color: #FFBA00;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QListView {\n"
            "    padding: 2px;\n"
            "    background: #F2F4F3;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QLabel, QLineEdit {\n"
            "    border: 2px solid #F2F4F3;\n"
            "    border-radius: 5px;\n"
            "    font-size: 14pt;\n"
            "    padding: 2px;\n"
            "    padding-left: 5px;\n"
            "    background-color: #F2F4F3;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QTextEdit, QListWidget {\n"
            "    border: 0px;\n"
            "    border-radius: 5px;\n"
            "    font-size: 12pt;\n"
            "    padding: 2px;\n"
            "    padding-left: 5px;\n"
            "    background-color: #F2F4F3;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QPushButton {\n"
            "    background-color: #FFBA00;\n"
            "    border-radius: 5px;\n"
            "    font-size: 14pt;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #FFC300;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #ab7b00;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QSlider {\n"
            "    background: #5d707f;\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal, QSlider::handle:vertical {\n"
            "    background-color: #FFBA00;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QSpinBox, QDoubleSpinBox {\n"
            "    border: 2px solid #F2F4F3;\n"
            "    border-radius: 5px;\n"
            "    border-width: 3px;\n"
            "    border-top-right-radius: 0;\n"
            "    border-bottom-right-radius: 0;\n"
            "    font-size: 12pt;\n"
            "    padding: 2px;\n"
            "    padding-left: 5px;\n"
            "    padding-right: 5px;\n"
            "    background-color: #F2F4F3;\n"
            "}\n"
            "\n"
            "QSpinBox::up-button, QDoubleSpinBox::up-button { \n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: top right; /* position at the top right corner */\n"
            "    width: 30 px;\n"
            "}\n"
            "\n"
            "QSpinBox::down-button, QDoubleSpinBox::down-button { \n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: bottom right; /* position at the top right corner */\n"
            "    width: 30 px;\n"
            "    top: 1px;\n"
            "}\n"
            "\n"
            "QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
            "    image: url(:/images/up.png);\n"
            "}\n"
            "\n"
            "QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
            "    image: url(:/images/down.png);;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QScrollBar:vertical {  \n"
            "    border: None;\n"
            "    background:#f2f4f3;\n"
            "    width: 10px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical {\n"
            "    background:#ffba00;\n"
            "    border-radius: 4px;\n"
            "    min-height: 20px;\n"
            "}\n"
            "\n"
            "QScrollBar:horizontal {  \n"
            "    background:#f2f4f3;\n"
            "    height: 15px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal {\n"
            "    background:#ffba00;\n"
            "    border-radius: 4px;\n"
            "    min-width: 20px;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QTextEdit {\n"
            "    border: 2px solid #909cc2\n"
            "}\n"
            "\n"
            "QTextEdit:selected {\n"
            "    border-color: #aab9e6\n"
            "}"
        )
        self.mainframe.setObjectName("mainframe")
        self.CAM_disp_1 = QtWidgets.QLabel(self.mainframe)
        self.CAM_disp_1.setGeometry(QtCore.QRect(30, 20, 861, 451))
        self.CAM_disp_1.setObjectName("CAM_disp_1")
        self.CAM_disp_2 = QtWidgets.QLabel(self.mainframe)
        self.CAM_disp_2.setGeometry(QtCore.QRect(910, 20, 901, 451))
        self.CAM_disp_2.setObjectName("CAM_disp_2")
        self.CAM_disp_3 = QtWidgets.QLabel(self.mainframe)
        self.CAM_disp_3.setGeometry(QtCore.QRect(30, 490, 581, 451))
        self.CAM_disp_3.setObjectName("CAM_disp_3")
        self.label_4 = QtWidgets.QLabel(self.mainframe)
        self.label_4.setGeometry(QtCore.QRect(910, 490, 581, 451))
        self.label_4.setObjectName("label_4")
        # MainWindow.setCentralWidget(self.mainframe)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CAM_disp_1.setText(_translate("MainWindow", "TextLabel"))
        self.CAM_disp_2.setText(_translate("MainWindow", "TextLabel"))
        self.CAM_disp_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
