# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\connSetup_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CONN(object):
    def setupUi(self, CONN):
        CONN.setObjectName("CONN")
        CONN.resize(880, 787)
        CONN.setStyleSheet(
            "/* leave here to be overwritten by anything more specific */\n"
            "QObject {\n"
            "    background: #4c4a48;\n"
            "}\n"
            "\n"
            "QWidget {\n"
            '    font-family: "Bahnschrift";\n'
            "}\n"
            "\n"
            "\n"
            "\n"
            "/* alphabetical from here */\n"
            "\n"
            "QCheckBox::indicator {\n"
            "    width: 20px;\n"
            "    height: 20px;\n"
            "    background-color: #f2f4f3;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: #ffba00;\n"
            "    image: url(:/images/right.png);\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QComboBox {\n"
            "    border-radius: 5px;\n"
            "    padding-left: 10px;\n"
            "    min-width: 6em;\n"
            "    background: #F2F4F3;\n"
            '    font-family: "Bahnschrift";\n'
            "}\n"
            "\n"
            "QComboBox:on { /* shift the text when the popup opens */\n"
            "    border: 2px sold #F2F4F3;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down {\n"
            "    width: 25px;\n"
            "    background-color: #FFBA00;\n"
            "}\n"
            "\n"
            "QComboBox::down-arrow {\n"
            "    border-image: url(:/images/down.png);\n"
            "}\n"
            "\n"
            "QComboBox::drop-down::hover {\n"
            "    background-color: #FFC300;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down::pressed {\n"
            "    background-color: #88AB75;\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView {\n"
            "    selection-background-color: #FFBA00;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QListView {\n"
            "    padding: 2px;\n"
            "    background: #F2F4F3;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QLabel, QLineEdit {\n"
            "    border: 2px solid #F2F4F3;\n"
            "    border-radius: 5px;\n"
            "    font-size: 14pt;\n"
            "    padding: 2px;\n"
            "    padding-left: 5px;\n"
            "    background-color: #F2F4F3;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QTextEdit, QListWidget {\n"
            "    border: 0px;\n"
            "    border-radius: 5px;\n"
            "    font-size: 12pt;\n"
            "    padding: 2px;\n"
            "    padding-left: 5px;\n"
            "    background-color: #F2F4F3;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QPushButton {\n"
            "    background-color: #FFBA00;\n"
            "    border-radius: 5px;\n"
            "    font-size: 14pt;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #FFC300;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #88AB75;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QSlider {\n"
            "    background: #5d707f;\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal, QSlider::handle:vertical {\n"
            "    background-color: #FFBA00;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QSpinBox, QDoubleSpinBox {\n"
            "    border: 2px solid #F2F4F3;\n"
            "    border-radius: 5px;\n"
            "    border-width: 3px;\n"
            "    border-top-right-radius: 0;\n"
            "    border-bottom-right-radius: 0;\n"
            "    font-size: 12pt;\n"
            "    padding: 2px;\n"
            "    padding-left: 5px;\n"
            "    padding-right: 5px;\n"
            "    background-color: #F2F4F3;\n"
            "}\n"
            "\n"
            "QSpinBox::up-button, QDoubleSpinBox::up-button { \n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: top right; /* position at the top right corner */\n"
            "    width: 30 px;\n"
            "}\n"
            "\n"
            "QSpinBox::down-button, QDoubleSpinBox::down-button { \n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: bottom right; /* position at the top right corner */\n"
            "    width: 30 px;\n"
            "    top: 1px;\n"
            "}\n"
            "\n"
            "QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
            "    image: url(:/images/up.png);\n"
            "}\n"
            "\n"
            "QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
            "    image: url(:/images/down.png);;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QScrollBar:vertical {  \n"
            "    border: None;\n"
            "    background:#f2f4f3;\n"
            "    width: 10px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical {\n"
            "    background:#ffba00;\n"
            "    border-radius: 4px;\n"
            "    min-height: 20px;\n"
            "}\n"
            "\n"
            "QScrollBar:horizontal {  \n"
            "    background:#f2f4f3;\n"
            "    height: 15px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle:horizontal {\n"
            "    background:#ffba00;\n"
            "    border-radius: 4px;\n"
            "    min-width: 20px;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QTextEdit {\n"
            "    border: 2px solid #909cc2\n"
            "}\n"
            "\n"
            "QTextEdit:selected {\n"
            "    border-color: #aab9e6\n"
            "}"
        )
        self.CONN_bttbox = QtWidgets.QDialogButtonBox(CONN)
        self.CONN_bttbox.setGeometry(QtCore.QRect(260, 710, 571, 51))
        self.CONN_bttbox.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #FFBA00;\n"
            "    color: #000000;\n"
            "    border-radius: 5px;\n"
            "    font-size: 14pt;\n"
            "    width: 5em;\n"
            "    height: 35px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #FFC300;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #88AB75;\n"
            "}"
        )
        self.CONN_bttbox.setOrientation(QtCore.Qt.Horizontal)
        self.CONN_bttbox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Abort | QtWidgets.QDialogButtonBox.Ok
        )
        self.CONN_bttbox.setCenterButtons(False)
        self.CONN_bttbox.setObjectName("CONN_bttbox")
        self.ROB_lbl_connTo = QtWidgets.QLabel(CONN)
        self.ROB_lbl_connTo.setGeometry(QtCore.QRect(500, 150, 151, 30))
        self.ROB_lbl_connTo.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.ROB_lbl_connTo.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.ROB_lbl_connTo.setObjectName("ROB_lbl_connTo")
        self.ROB_lbl_port = QtWidgets.QLabel(CONN)
        self.ROB_lbl_port.setGeometry(QtCore.QRect(700, 50, 131, 30))
        self.ROB_lbl_port.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.ROB_lbl_port.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.ROB_lbl_port.setObjectName("ROB_lbl_port")
        self.ROB_lbl_rwTo = QtWidgets.QLabel(CONN)
        self.ROB_lbl_rwTo.setGeometry(QtCore.QRect(690, 150, 141, 30))
        self.ROB_lbl_rwTo.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.ROB_lbl_rwTo.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.ROB_lbl_rwTo.setObjectName("ROB_lbl_rwTo")
        self.ROB_lbl_ip = QtWidgets.QLabel(CONN)
        self.ROB_lbl_ip.setGeometry(QtCore.QRect(450, 50, 131, 30))
        self.ROB_lbl_ip.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.ROB_lbl_ip.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.ROB_lbl_ip.setObjectName("ROB_lbl_ip")
        self.ROB_lbl = QtWidgets.QLabel(CONN)
        self.ROB_lbl.setGeometry(QtCore.QRect(70, 80, 161, 51))
        self.ROB_lbl.setStyleSheet(
            "background: #5d707f;\n" "color: #f2f4f3;\n" "font-size: 20pt;"
        )
        self.ROB_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ROB_lbl.setObjectName("ROB_lbl")
        self.P1_lbl = QtWidgets.QLabel(CONN)
        self.P1_lbl.setGeometry(QtCore.QRect(70, 280, 161, 51))
        self.P1_lbl.setStyleSheet(
            "background: #5d707f;\n" "color: #f2f4f3;\n" "font-size: 20pt;"
        )
        self.P1_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.P1_lbl.setObjectName("P1_lbl")
        self.P1_lbl_port = QtWidgets.QLabel(CONN)
        self.P1_lbl_port.setGeometry(QtCore.QRect(606, 295, 91, 30))
        self.P1_lbl_port.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.P1_lbl_port.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
        )
        self.P1_lbl_port.setObjectName("P1_lbl_port")
        self.ROB_entry_ip = QtWidgets.QLineEdit(CONN)
        self.ROB_entry_ip.setGeometry(QtCore.QRect(450, 80, 231, 51))
        self.ROB_entry_ip.setStyleSheet("font-size: 18pt;")
        self.ROB_entry_ip.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ROB_entry_ip.setObjectName("ROB_entry_ip")
        self.ROB_entry_port = QtWidgets.QLineEdit(CONN)
        self.ROB_entry_port.setGeometry(QtCore.QRect(700, 80, 131, 51))
        self.ROB_entry_port.setStyleSheet("font-size: 18pt;")
        self.ROB_entry_port.setObjectName("ROB_entry_port")
        self.P1_entry_port = QtWidgets.QLineEdit(CONN)
        self.P1_entry_port.setGeometry(QtCore.QRect(700, 280, 131, 51))
        self.P1_entry_port.setStyleSheet("font-size: 18pt;\n" "")
        self.P1_entry_port.setObjectName("P1_entry_port")
        self.ROB_num_rwTo = QtWidgets.QSpinBox(CONN)
        self.ROB_num_rwTo.setGeometry(QtCore.QRect(690, 180, 141, 41))
        self.ROB_num_rwTo.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ROB_num_rwTo.setMaximum(99999)
        self.ROB_num_rwTo.setObjectName("ROB_num_rwTo")
        self.ROB_num_connTo = QtWidgets.QSpinBox(CONN)
        self.ROB_num_connTo.setGeometry(QtCore.QRect(500, 180, 151, 41))
        self.ROB_num_connTo.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ROB_num_connTo.setMaximum(99999)
        self.ROB_num_connTo.setObjectName("ROB_num_connTo")
        self.P1_chk_available = QtWidgets.QCheckBox(CONN)
        self.P1_chk_available.setGeometry(QtCore.QRect(260, 300, 131, 20))
        self.P1_chk_available.setStyleSheet(
            "QCheckBox {\n" "    color: #f2f4f3;\n" "    font-size: 14pt;\n" "}\n" ""
        )
        self.P1_chk_available.setObjectName("P1_chk_available")
        self.CONN_btt_default = QtWidgets.QPushButton(CONN)
        self.CONN_btt_default.setGeometry(QtCore.QRect(70, 720, 211, 35))
        self.CONN_btt_default.setObjectName("CONN_btt_default")
        self.ROB_lbl_colon = QtWidgets.QLabel(CONN)
        self.ROB_lbl_colon.setGeometry(QtCore.QRect(679, 88, 21, 30))
        self.ROB_lbl_colon.setStyleSheet(
            "border: 0px;\n"
            "font-size: 14pt;\n"
            "font: bold;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.ROB_lbl_colon.setAlignment(QtCore.Qt.AlignCenter)
        self.ROB_lbl_colon.setObjectName("ROB_lbl_colon")
        self.P2_lbl_port = QtWidgets.QLabel(CONN)
        self.P2_lbl_port.setGeometry(QtCore.QRect(606, 395, 91, 30))
        self.P2_lbl_port.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.P2_lbl_port.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
        )
        self.P2_lbl_port.setObjectName("P2_lbl_port")
        self.P2_lbl = QtWidgets.QLabel(CONN)
        self.P2_lbl.setGeometry(QtCore.QRect(73, 380, 161, 51))
        self.P2_lbl.setStyleSheet(
            "background: #5d707f;\n" "color: #f2f4f3;\n" "font-size: 20pt;"
        )
        self.P2_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.P2_lbl.setObjectName("P2_lbl")
        self.P2_entry_port = QtWidgets.QLineEdit(CONN)
        self.P2_entry_port.setGeometry(QtCore.QRect(700, 380, 131, 51))
        self.P2_entry_port.setStyleSheet("font-size: 18pt;")
        self.P2_entry_port.setObjectName("P2_entry_port")
        self.P2_chk_available = QtWidgets.QCheckBox(CONN)
        self.P2_chk_available.setGeometry(QtCore.QRect(260, 400, 131, 20))
        self.P2_chk_available.setStyleSheet(
            "QCheckBox {\n" "    color: #f2f4f3;\n" "    font-size: 14pt;\n" "}\n" ""
        )
        self.P2_chk_available.setObjectName("P2_chk_available")
        self.PRH_lbl = QtWidgets.QLabel(CONN)
        self.PRH_lbl.setGeometry(QtCore.QRect(70, 490, 161, 51))
        self.PRH_lbl.setStyleSheet(
            "background: #5d707f;\n" "color: #f2f4f3;\n" "font-size: 20pt;"
        )
        self.PRH_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.PRH_lbl.setObjectName("PRH_lbl")
        self.PRH_lbl_port = QtWidgets.QLabel(CONN)
        self.PRH_lbl_port.setGeometry(QtCore.QRect(700, 460, 131, 30))
        self.PRH_lbl_port.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.PRH_lbl_port.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.PRH_lbl_port.setObjectName("PRH_lbl_port")
        self.PRH_lbl_ip = QtWidgets.QLabel(CONN)
        self.PRH_lbl_ip.setGeometry(QtCore.QRect(450, 460, 131, 30))
        self.PRH_lbl_ip.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.PRH_lbl_ip.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.PRH_lbl_ip.setObjectName("PRH_lbl_ip")
        self.PRH_entry_ip = QtWidgets.QLineEdit(CONN)
        self.PRH_entry_ip.setGeometry(QtCore.QRect(450, 490, 231, 51))
        self.PRH_entry_ip.setStyleSheet("font-size: 18pt;")
        self.PRH_entry_ip.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.PRH_entry_ip.setObjectName("PRH_entry_ip")
        self.PRH_lbl_colon = QtWidgets.QLabel(CONN)
        self.PRH_lbl_colon.setGeometry(QtCore.QRect(679, 498, 21, 30))
        self.PRH_lbl_colon.setStyleSheet(
            "border: 0px;\n"
            "font-size: 14pt;\n"
            "font: bold;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.PRH_lbl_colon.setAlignment(QtCore.Qt.AlignCenter)
        self.PRH_lbl_colon.setObjectName("PRH_lbl_colon")
        self.PRH_entry_port = QtWidgets.QLineEdit(CONN)
        self.PRH_entry_port.setGeometry(QtCore.QRect(700, 490, 131, 51))
        self.PRH_entry_port.setStyleSheet("font-size: 18pt;")
        self.PRH_entry_port.setObjectName("PRH_entry_port")
        self.DB_lbl_ip = QtWidgets.QLabel(CONN)
        self.DB_lbl_ip.setGeometry(QtCore.QRect(450, 560, 131, 30))
        self.DB_lbl_ip.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.DB_lbl_ip.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.DB_lbl_ip.setObjectName("DB_lbl_ip")
        self.DB_lbl_colon = QtWidgets.QLabel(CONN)
        self.DB_lbl_colon.setGeometry(QtCore.QRect(679, 598, 21, 30))
        self.DB_lbl_colon.setStyleSheet(
            "border: 0px;\n"
            "font-size: 14pt;\n"
            "font: bold;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.DB_lbl_colon.setAlignment(QtCore.Qt.AlignCenter)
        self.DB_lbl_colon.setObjectName("DB_lbl_colon")
        self.DB_lbl_port = QtWidgets.QLabel(CONN)
        self.DB_lbl_port.setGeometry(QtCore.QRect(700, 560, 131, 30))
        self.DB_lbl_port.setStyleSheet(
            "border: 0px;\n"
            "font-size: 12pt;\n"
            "background-color: #4c4a48;\n"
            "color: #E1E5EE;"
        )
        self.DB_lbl_port.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.DB_lbl_port.setObjectName("DB_lbl_port")
        self.DB_entry_port = QtWidgets.QLineEdit(CONN)
        self.DB_entry_port.setGeometry(QtCore.QRect(700, 590, 131, 51))
        self.DB_entry_port.setStyleSheet("font-size: 18pt;")
        self.DB_entry_port.setObjectName("DB_entry_port")
        self.DB_lbl = QtWidgets.QLabel(CONN)
        self.DB_lbl.setGeometry(QtCore.QRect(70, 590, 161, 51))
        self.DB_lbl.setStyleSheet(
            "background: #5d707f;\n" "color: #f2f4f3;\n" "font-size: 20pt;"
        )
        self.DB_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.DB_lbl.setObjectName("DB_lbl")
        self.DB_entry_ip = QtWidgets.QLineEdit(CONN)
        self.DB_entry_ip.setGeometry(QtCore.QRect(450, 590, 231, 51))
        self.DB_entry_ip.setStyleSheet("font-size: 18pt;")
        self.DB_entry_ip.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.DB_entry_ip.setObjectName("DB_entry_ip")
        self.ROB_chk_available = QtWidgets.QCheckBox(CONN)
        self.ROB_chk_available.setGeometry(QtCore.QRect(260, 100, 131, 20))
        self.ROB_chk_available.setStyleSheet(
            "QCheckBox {\n" "    color: #f2f4f3;\n" "    font-size: 14pt;\n" "}\n" ""
        )
        self.ROB_chk_available.setObjectName("ROB_chk_available")
        self.PRH_chk_available = QtWidgets.QCheckBox(CONN)
        self.PRH_chk_available.setGeometry(QtCore.QRect(260, 510, 131, 20))
        self.PRH_chk_available.setStyleSheet(
            "QCheckBox {\n" "    color: #f2f4f3;\n" "    font-size: 14pt;\n" "}\n" ""
        )
        self.PRH_chk_available.setObjectName("PRH_chk_available")
        self.DB_chk_available = QtWidgets.QCheckBox(CONN)
        self.DB_chk_available.setEnabled(False)
        self.DB_chk_available.setGeometry(QtCore.QRect(260, 610, 131, 20))
        self.DB_chk_available.setStyleSheet(
            "QCheckBox {\n" "    color: #c2c4c3;\n" "    font-size: 14pt;\n" "}\n" ""
        )
        self.DB_chk_available.setChecked(True)
        self.DB_chk_available.setObjectName("DB_chk_available")
        self.PRH_lbl_colon.raise_()
        self.ROB_lbl_colon.raise_()
        self.CONN_bttbox.raise_()
        self.ROB_lbl_connTo.raise_()
        self.ROB_lbl_port.raise_()
        self.ROB_lbl_rwTo.raise_()
        self.ROB_lbl_ip.raise_()
        self.ROB_lbl.raise_()
        self.P1_lbl.raise_()
        self.P1_lbl_port.raise_()
        self.ROB_entry_ip.raise_()
        self.ROB_entry_port.raise_()
        self.P1_entry_port.raise_()
        self.ROB_num_rwTo.raise_()
        self.ROB_num_connTo.raise_()
        self.P1_chk_available.raise_()
        self.CONN_btt_default.raise_()
        self.P2_lbl_port.raise_()
        self.P2_lbl.raise_()
        self.P2_entry_port.raise_()
        self.P2_chk_available.raise_()
        self.PRH_lbl.raise_()
        self.PRH_lbl_port.raise_()
        self.PRH_lbl_ip.raise_()
        self.PRH_entry_ip.raise_()
        self.PRH_entry_port.raise_()
        self.DB_lbl_ip.raise_()
        self.DB_lbl_colon.raise_()
        self.DB_lbl_port.raise_()
        self.DB_entry_port.raise_()
        self.DB_lbl.raise_()
        self.DB_entry_ip.raise_()
        self.ROB_chk_available.raise_()
        self.PRH_chk_available.raise_()
        self.DB_chk_available.raise_()

        self.retranslateUi(CONN)
        self.CONN_bttbox.accepted.connect(CONN.accept)  # type: ignore
        self.CONN_bttbox.rejected.connect(CONN.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CONN)

    def retranslateUi(self, CONN):
        _translate = QtCore.QCoreApplication.translate
        CONN.setWindowTitle(_translate("CONN", "Dialog"))
        self.ROB_lbl_connTo.setText(_translate("CONN", "conn timeout [ms]"))
        self.ROB_lbl_port.setText(_translate("CONN", "port"))
        self.ROB_lbl_rwTo.setText(_translate("CONN", "r/w timeout [ms]"))
        self.ROB_lbl_ip.setText(_translate("CONN", "IP"))
        self.ROB_lbl.setText(_translate("CONN", "ROBOT"))
        self.P1_lbl.setText(_translate("CONN", "PUMP 1"))
        self.P1_lbl_port.setText(_translate("CONN", "COM port"))
        self.ROB_entry_ip.setText(_translate("CONN", "192.168.178.125"))
        self.ROB_entry_port.setText(_translate("CONN", "10001"))
        self.P1_entry_port.setText(_translate("CONN", "COM3"))
        self.P1_chk_available.setText(_translate("CONN", "available"))
        self.CONN_btt_default.setText(_translate("CONN", "Voreinstellungen"))
        self.ROB_lbl_colon.setText(_translate("CONN", ":"))
        self.P2_lbl_port.setText(_translate("CONN", "COM port"))
        self.P2_lbl.setText(_translate("CONN", "PUMP 2"))
        self.P2_entry_port.setText(_translate("CONN", "COM3"))
        self.P2_chk_available.setText(_translate("CONN", "available"))
        self.PRH_lbl.setText(_translate("CONN", "PRINTHEAD"))
        self.PRH_lbl_port.setText(_translate("CONN", "port"))
        self.PRH_lbl_ip.setText(_translate("CONN", "IP"))
        self.PRH_entry_ip.setText(_translate("CONN", "192.168.178.58"))
        self.PRH_lbl_colon.setText(_translate("CONN", ":"))
        self.PRH_entry_port.setText(_translate("CONN", "17"))
        self.DB_lbl_ip.setText(_translate("CONN", "IP"))
        self.DB_lbl_colon.setText(_translate("CONN", ":"))
        self.DB_lbl_port.setText(_translate("CONN", "port"))
        self.DB_entry_port.setText(_translate("CONN", "8086"))
        self.DB_lbl.setText(_translate("CONN", "DATABASE"))
        self.DB_entry_ip.setText(_translate("CONN", "192.168.178.56"))
        self.ROB_chk_available.setText(_translate("CONN", "available"))
        self.PRH_chk_available.setText(_translate("CONN", "available"))
        self.DB_chk_available.setText(_translate("CONN", "available"))


import resources
